export const mockdata = [
  { admid: 1, name: "Alice Johnson", grade_class: "10-A", house: "WINTER", voted: "NOT VOTED", absent: "PRESENT" },
  { admid: 2, name: "Benjamin Smith", grade_class: "10-B", house: "SUMMER", voted: "VOTED", absent: "PRESENT" },
  { admid: 3, name: "Charlotte Davis", grade_class: "11-A", house: "SPRING", voted: "NOT VOTED", absent: "PRESENT" },
  { admid: 4, name: "Daniel Wilson", grade_class: "11-B", house: "WINTER", voted: "VOTED", absent: "PRESENT" },
  { admid: 5, name: "Emma Taylor", grade_class: "12-A", house: "SUMMER", voted: "NOT VOTED", absent: "ABSENT" },
  { admid: 6, name: "Felix Anderson", grade_class: "12-B", house: "SPRING", voted: "VOTED", absent: "PRESENT" },
  { admid: 7, name: "Grace Thomas", grade_class: "9-A", house: "WINTER", voted: "NOT VOTED", absent: "PRESENT" },
  { admid: 8, name: "Henry Moore", grade_class: "9-B", house: "SUMMER", voted: "VOTED", absent: "PRESENT" },
  { admid: 9, name: "Isabella Martin", grade_class: "10-A", house: "SPRING", voted: "NOT VOTED", absent: "PRESENT" },
  { admid: 10, name: "Jack White", grade_class: "10-B", house: "WINTER", voted: "VOTED", absent: "ABSENT" },

  { admid: 11, name: "Katherine Hall", grade_class: "11-A", house: "SUMMER", voted: "NOT VOTED", absent: "PRESENT" },
  { admid: 12, name: "Liam Walker", grade_class: "11-B", house: "SPRING", voted: "VOTED", absent: "PRESENT" },
  { admid: 13, name: "Mia Young", grade_class: "12-A", house: "WINTER", voted: "NOT VOTED", absent: "PRESENT" },
  { admid: 14, name: "Noah King", grade_class: "12-B", house: "SUMMER", voted: "VOTED", absent: "PRESENT" },
  { admid: 15, name: "Olivia Scott", grade_class: "9-A", house: "SPRING", voted: "NOT VOTED", absent: "ABSENT" },
  { admid: 16, name: "Patrick Green", grade_class: "9-B", house: "WINTER", voted: "VOTED", absent: "PRESENT" },
  { admid: 17, name: "Quinn Baker", grade_class: "10-A", house: "SUMMER", voted: "NOT VOTED", absent: "PRESENT" },
  { admid: 18, name: "Ryan Adams", grade_class: "10-B", house: "SPRING", voted: "VOTED", absent: "PRESENT" },
  { admid: 19, name: "Sophia Nelson", grade_class: "11-A", house: "WINTER", voted: "NOT VOTED", absent: "PRESENT" },
  { admid: 20, name: "Thomas Carter", grade_class: "11-B", house: "SUMMER", voted: "VOTED", absent: "ABSENT" },

  { admid: 21, name: "Uma Mitchell", grade_class: "12-A", house: "SPRING", voted: "NOT VOTED", absent: "PRESENT" },
  { admid: 22, name: "Victor Perez", grade_class: "12-B", house: "WINTER", voted: "VOTED", absent: "PRESENT" },
  { admid: 23, name: "Willow Roberts", grade_class: "9-A", house: "SUMMER", voted: "NOT VOTED", absent: "PRESENT" },
  { admid: 24, name: "Xavier Turner", grade_class: "9-B", house: "SPRING", voted: "VOTED", absent: "PRESENT" },
  { admid: 25, name: "Yara Phillips", grade_class: "10-A", house: "WINTER", voted: "NOT VOTED", absent: "ABSENT" },
  { admid: 26, name: "Zachary Campbell", grade_class: "10-B", house: "SUMMER", voted: "VOTED", absent: "PRESENT" },
  { admid: 27, name: "Ava Parker", grade_class: "11-A", house: "SPRING", voted: "NOT VOTED", absent: "PRESENT" },
  { admid: 28, name: "Blake Evans", grade_class: "11-B", house: "WINTER", voted: "VOTED", absent: "PRESENT" },
  { admid: 29, name: "Clara Edwards", grade_class: "12-A", house: "SUMMER", voted: "NOT VOTED", absent: "PRESENT" },
  { admid: 30, name: "Dylan Collins", grade_class: "12-B", house: "SPRING", voted: "VOTED", absent: "ABSENT" },

  { admid: 31, name: "Ella Stewart", grade_class: "9-A", house: "WINTER", voted: "NOT VOTED", absent: "PRESENT" },
  { admid: 32, name: "Finn Sanchez", grade_class: "9-B", house: "SUMMER", voted: "VOTED", absent: "PRESENT" },
  { admid: 33, name: "Gabriella Morris", grade_class: "10-A", house: "SPRING", voted: "NOT VOTED", absent: "PRESENT" },
  { admid: 34, name: "Hudson Rogers", grade_class: "10-B", house: "WINTER", voted: "VOTED", absent: "PRESENT" },
  { admid: 35, name: "Ivy Reed", grade_class: "11-A", house: "SUMMER", voted: "NOT VOTED", absent: "ABSENT" },
  { admid: 36, name: "Jason Cook", grade_class: "11-B", house: "SPRING", voted: "VOTED", absent: "PRESENT" },
  { admid: 37, name: "Kayla Morgan", grade_class: "12-A", house: "WINTER", voted: "NOT VOTED", absent: "PRESENT" },
  { admid: 38, name: "Logan Bell", grade_class: "12-B", house: "SUMMER", voted: "VOTED", absent: "PRESENT" },
  { admid: 39, name: "Madison Murphy", grade_class: "9-A", house: "SPRING", voted: "NOT VOTED", absent: "PRESENT" },
  { admid: 40, name: "Nathan Bailey", grade_class: "9-B", house: "WINTER", voted: "VOTED", absent: "ABSENT" },
];